# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         KSx-Search-WildCardQuery
version:      0.02
version_from: lib/KSx/Search/WildCardQuery.pm
installdirs:  site
requires:
    base:                          0
    Hash::Util::FieldHash::Compat: 0
    KinoSearch::Analysis::Tokenizer: 0
    KinoSearch::FieldType::FullTextType: 0
    KinoSearch::Indexer:           0
    KinoSearch::Schema:            0
    KinoSearch::Search::Compiler:  0
    KinoSearch::Search::Query:     0
    KinoSearch::Search::Scorer:    0
    KinoSearch::Search::Span:      0
    KinoSearch::Search::Tally:     0
    KinoSearch::Searcher:          0
    KinoSearch::Store::RAMFolder:  0
    strict:                        0
    Test::More:                    0
    utf8:                          0
    warnings:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
